import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'menu': 'Menu',
      'cart': 'Cart',
      'total': 'Total',
      'submit_order': 'SUBMIT ORDER',
      'cart_empty': 'Cart is Empty',
      'current_order': 'Current Order',
      'no_items': 'No Items Found',
      'no_items_msg': 'There are no items in this category yet.',
      'error_title': 'Oops! Something went wrong',
      'order_sent': 'Order Sent to Kitchen!',
      'everyone_favs': 'Everyone\'s Favorites',
      'new_delicacy': 'NEW DELICACY',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'add_photo': 'ADD PHOTO',
      'category_label': 'CATEGORY',
      'category_hint': 'e.g., Signature Dishes',
      'dish_name_label': 'DISH NAME',
      'dish_name_hint': 'e.g., Golden Saffron Risotto',
      'description_label': 'DESCRIPTION',
      'description_hint': 'Describe the sensory experience...',
      'price_label': 'PRICE',
      'available_label': 'AVAILABLE',
      'save_to_menu': 'SAVE TO MENU',
      'select_image': 'Please select an image',
      'delicacy_added': 'Delicacy Added Successfully!',
      'required_field': 'Required',
      'invalid_price': 'Invalid Price',
      'error': 'Error: ',
      'your_order': 'YOUR ORDER',
      'bag_empty': 'YOUR BAG IS EMPTY',
      'back_to_menu': 'BACK TO MENU',
      'place_order': 'PLACE ORDER',
      'clear_order_title': 'Clear Order?',
      'clear_order_msg': 'Remove all items from your bag?',
      'cancel': 'Cancel',
      'clear': 'Clear',
      'order_placed': 'ORDER PLACED',
      'order_placed_msg': 'Your selection is being prepared.',
      'excellent': 'Excellent',
      'order_history': 'ORDER HISTORY',
      'order_history_desc': 'View completed orders',
      'no_orders': 'NO ORDERS YET',
      'no_orders_msg': 'Your order history will appear here.',
      'clear_history': 'Clear History?',
      'clear_history_msg': 'Remove all past orders?',
      'pending': 'Pending',
      'preparing': 'Preparing',
      'ready': 'Ready',
      'completed': 'Completed',
      'item_added': 'added',
      'undo': 'UNDO',
      'sold_out': 'SOLD OUT',
      'add_to_order': 'ADD TO ORDER',
      'permission_denied': 'Permission denied. Please allow access in settings.',
      'settings': 'Settings',
      'admin_login': 'Admin Login',
      'admin_panel': 'Admin Panel',
      'username': 'Username',
      'password': 'Password',
      'login': 'Login',
      'login_failed': 'Invalid username or password',
      'product_management': 'Product Management',
      'manage_products_desc': 'View and manage all products',
      'category_management': 'Category Management',
      'manage_categories_desc': 'Add and edit categories',
      'change_password': 'Change Password',
      'change_password_desc': 'Update your admin password',
      'logout': 'Logout',
      'logout_desc': 'Sign out from admin panel',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'password_too_short': 'Password must be at least 6 characters',
      'passwords_not_match': 'Passwords do not match',
      'password_changed': 'Password changed successfully',
      'incorrect_password': 'Incorrect current password',
      'change': 'Change',
      'no_products': 'No products found',
      'search_products': 'Search products...',
      'all_categories': 'All Categories',
      'no_results': 'No results found',
      'add_category': 'Add Category',
      'category_name': 'Category Name',
      'category_exists': 'Category already exists',
      'category_added': 'Category added successfully',
      'add': 'Add',
      'edit_category': 'Edit Category',
      'save': 'Save',
      'category_updated': 'Category updated successfully',
      'delete_category': 'Delete Category',
      'delete_category_confirm': 'Are you sure you want to delete this category?',
      'category_deleted': 'Category deleted',
      'delete': 'Delete',
      'no_categories': 'No categories found',
    },
    'ru': {
      'menu': 'Меню',
      'cart': 'Корзина',
      'total': 'Итого',
      'submit_order': 'ОФОРМИТЬ ЗАКАЗ',
      'cart_empty': 'Корзина пуста',
      'current_order': 'Текущий заказ',
      'no_items': 'Ничего не найдено',
      'no_items_msg': 'В этой категории пока нет товаров.',
      'error_title': 'Ой! Что-то пошло не так',
      'order_sent': 'Заказ отправлен на кухню!',
      'everyone_favs': 'Популярное',
      'new_delicacy': 'НОВЫЙ ДЕЛИКАТЕС',
      'gallery': 'Галерея',
      'camera': 'Камера',
      'add_photo': 'ДОБАВИТЬ ФОТО',
      'category_label': 'КАТЕГОРИЯ',
      'category_hint': 'напр., Фирменные блюда',
      'dish_name_label': 'НАЗВАНИЕ БЛЮДА',
      'dish_name_hint': 'напр., Золотое ризотто с шафраном',
      'description_label': 'ОПИСАНИЕ',
      'description_hint': 'Опишите вкусовые качества...',
      'price_label': 'ЦЕНА',
      'available_label': 'ДОСТУПНО',
      'save_to_menu': 'СОХРАНИТЬ В МЕНЮ',
      'select_image': 'Пожалуйста, выберите изображение',
      'delicacy_added': 'Деликатес успешно добавлен!',
      'required_field': 'Обязательно',
      'invalid_price': 'Неверная цена',
      'error': 'Ошибка: ',
      'your_order': 'ВАШ ЗАКАЗ',
      'bag_empty': 'ВАША КОРЗИНА ПУСТА',
      'back_to_menu': 'В МЕНЮ',
      'place_order': 'ОФОРМИТЬ',
      'clear_order_title': 'Очистить заказ?',
      'clear_order_msg': 'Удалить все товары?',
      'cancel': 'Отмена',
      'clear': 'Очистить',
      'order_placed': 'ЗАКАЗ ОФОРМЛЕН',
      'order_placed_msg': 'Ваш заказ готовится.',
      'excellent': 'Отлично',
      'order_history': 'ИСТОРИЯ ЗАКАЗОВ',
      'order_history_desc': 'Просмотр выполненных заказов',
      'no_orders': 'ЗАКАЗОВ НЕТ',
      'no_orders_msg': 'История заказов появится здесь.',
      'clear_history': 'Очистить историю?',
      'clear_history_msg': 'Удалить все прошлые заказы?',
      'pending': 'В ожидании',
      'preparing': 'Готовится',
      'ready': 'Готово',
      'completed': 'Завершено',
      'item_added': 'добавлено',
      'undo': 'ОТМЕНА',
      'sold_out': 'ПРОДАНО',
      'add_to_order': 'В ЗАКАЗ',
      'permission_denied': 'Доступ запрещен. Разрешите доступ в настройках.',
      'settings': 'Настройки',
      'admin_login': 'Вход админа',
      'admin_panel': 'Панель админа',
      'username': 'Имя пользователя',
      'password': 'Пароль',
      'login': 'Войти',
      'login_failed': 'Неверное имя или пароль',
      'product_management': 'Управление продуктами',
      'manage_products_desc': 'Просмотр и управление товарами',
      'category_management': 'Управление категориями',
      'manage_categories_desc': 'Добавление и редактирование категорий',
      'change_password': 'Изменить пароль',
      'change_password_desc': 'Обновить пароль администратора',
      'logout': 'Выйти',
      'logout_desc': 'Выйти из панели администратора',
      'current_password': 'Текущий пароль',
      'new_password': 'Новый пароль',
      'confirm_password': 'Подтвердите пароль',
      'password_too_short': 'Пароль должен быть не менее 6 символов',
      'passwords_not_match': 'Пароли не совпадают',
      'password_changed': 'Пароль успешно изменен',
      'incorrect_password': 'Неверный текущий пароль',
      'change': 'Изменить',
      'no_products': 'Продукты не найдены',
      'search_products': 'Поиск товаров...',
      'all_categories': 'Все категории',
      'no_results': 'Результаты не найдены',
      'add_category': 'Добавить категорию',
      'category_name': 'Название категории',
      'category_exists': 'Категория уже существует',
      'category_added': 'Категория успешно добавлена',
      'add': 'Добавить',
      'edit_category': 'Редактировать категорию',
      'save': 'Сохранить',
      'category_updated': 'Категория обновлена',
      'delete_category': 'Удалить категорию',
      'delete_category_confirm': 'Вы уверены, что хотите удалить эту категорию?',
      'category_deleted': 'Категория удалена',
      'delete': 'Удалить',
      'no_categories': 'Категории не найдены',
    },
    'tk': {
      'menu': 'Menu',
      'cart': 'Sebet',
      'total': 'Jemi',
      'submit_order': 'SARGYT ETMEK',
      'cart_empty': 'Sebet boş',
      'current_order': 'Häzirki sargyt',
      'no_items': 'Haryt tapylmady',
      'no_items_msg': 'Bu kategoriýada entek haryt ýok.',
      'error_title': 'Bagyşlaň! Bir zat ýalňyş boldy',
      'order_sent': 'Sargyt aşhana ugradyldy!',
      'everyone_favs': 'Hemmäniň halanýanlary',
      'new_delicacy': 'TÄZE TAGAM',
      'gallery': 'Galereýa',
      'camera': 'Kamera',
      'add_photo': 'SURAT GOŞ',
      'category_label': 'KATEGORIÝA',
      'category_hint': 'meselem, Aýratyn tagamlar',
      'dish_name_label': 'TAGAM ADY',
      'dish_name_hint': 'meselem, Altyn şafran rizotto',
      'description_label': 'DÜŞÜNDIRIŞ',
      'description_hint': 'Tagamyň aýratynlyklaryny düşündiriň...',
      'price_label': 'BAHASY',
      'available_label': 'ELÝETERLI',
      'save_to_menu': 'MENÝUWA GOŞ',
      'select_image': 'Surat saýlaň',
      'delicacy_added': 'Tagam üstünlikli goşuldy!',
      'required_field': 'Hökmany',
      'invalid_price': 'Nädogry baha',
      'error': 'Ýalňyşlyk: ',
      'your_order': 'SARGYDYŇYZ',
      'bag_empty': 'SEBEDIŇIZ BOŞ',
      'back_to_menu': 'MENÝUWA DOLAN',
      'place_order': 'SARGYT ET',
      'clear_order_title': 'Sargydy bozmak?',
      'clear_order_msg': 'Sebetdäki ähli harytlary aýyrmalymy?',
      'cancel': 'Goýbolsun',
      'clear': 'Arassala',
      'order_placed': 'SARGYT EDILDI',
      'order_placed_msg': 'Sargydyňyz taýýarlanylýar.',
      'excellent': 'Ajaýyp',
      'order_history': 'SARGYT TARYHY',
      'order_history_desc': 'Soňky sargytlary gör',
      'no_orders': 'SARGYT ÝOK',
      'no_orders_msg': 'Sargyt taryhyňyz şu ýerde görkeziler.',
      'clear_history': 'Taryhy arassalamak?',
      'clear_history_msg': 'Ähli öňki sargytlary pozmalymy?',
      'pending': 'Garaşylýar',
      'preparing': 'Taýýarlanýar',
      'ready': 'Taýýar',
      'completed': 'Tamamlandy',
      'item_added': 'goşuldy',
      'undo': 'YZA AL',
      'sold_out': 'SATYLDY',
      'add_to_order': 'SARGYT ET',
      'permission_denied': 'Rugsat berilmedi. Sazlamalarda rugsat beriň.',
      'settings': 'Sazlamalar',
      'admin_login': 'Admin girmek',
      'admin_panel': 'Admin paneli',
      'username': 'Ulanyjy ady',
      'password': 'Parol',
      'login': 'Gir',
      'login_failed': 'Nädogry ulanyjy ady ýa-da parol',
      'product_management': 'Haryt dolandyryşy',
      'manage_products_desc': 'Harytlary görmek we dolandyrmak',
      'category_management': 'Kategoriýa dolandyryşy',
      'manage_categories_desc': 'Kategoriýa goşmak we düzetmek',
      'change_password': 'Parol üýtget',
      'change_password_desc': 'Admin parolyňyzy täzeläň',
      'logout': 'Çykmak',
      'logout_desc': 'Admin panelinden çykmak',
      'current_password': 'Häzirki parol',
      'new_password': 'Täze parol',
      'confirm_password': 'Paroly tassykla',
      'password_too_short': 'Parol azyndan 6 harpdan ybarat bolmaly',
      'passwords_not_match': 'Parollar gabat gelenok',
      'password_changed': 'Parol üstünlikli üýtgedildi',
      'incorrect_password': 'Nädogry häzirki parol',
      'change': 'Üýtget',
      'no_products': 'Haryt tapylmady',
      'search_products': 'Harytlary gözle...',
      'all_categories': 'Ähli kategoriýalar',
      'no_results': 'Netije tapylmady',
      'add_category': 'Kategoriýa goş',
      'category_name': 'Kategoriýa ady',
      'category_exists': 'Kategoriýa eýýäm bar',
      'category_added': 'Kategoriýa üstünlikli goşuldy',
      'add': 'Goş',
      'edit_category': 'Kategoriýany düzet',
      'save': 'Ýatda sakla',
      'category_updated': 'Kategoriýa täzelendi',
      'delete_category': 'Kategoriýany poz',
      'delete_category_confirm': 'Bu kategoriýany pozmak isleýärsiňizmi?',
      'category_deleted': 'Kategoriýa pozuldy',
      'delete': 'Poz',
      'no_categories': 'Kategoriýa tapylmady',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ru', 'tk'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

class TkMaterialLocalizationsDelegate extends LocalizationsDelegate<MaterialLocalizations> {
  const TkMaterialLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => locale.languageCode == 'tk';

  @override
  Future<MaterialLocalizations> load(Locale locale) async {
    return DefaultMaterialLocalizations.load(const Locale('en'));
  }

  @override
  bool shouldReload(TkMaterialLocalizationsDelegate old) => false;
}
